package template

var _headerTemplate = `
// Code generated by champ tool dtogen. DO NOT EDIT.

NEWLINE
/* 
  Package {{.PkgName}} is a generated mc cache package.
  It is generated from:
  ARGS
*/
NEWLINE

package {{.PkgName}}

import (
	"context"
	"fmt"
	{{if .UseStrConv}}"strconv"{{end}}
	{{if .EnableBatch }}"sync"{{end}}
NEWLINE
	{{.ImportPackage}}
)

`

var _addDtoTemplate = `
// {{.StructName}} created

type {{.StructName}} struct {
	{{.Fields}}
}

`
var _fieldTemplate = `
	{{.FiledName}} {{.Types}} {{.Tags}}
`
